name: JMeter Test Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  jmeter-test:
    runs-on: ubuntu-latest  # This is the environment for the job (Ubuntu)

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install Java (required by JMeter)
    - name: Install OpenJDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
    
    # Step 3: Download and install JMeter
    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        sudo mv apache-jmeter-5.4.1 /opt/jmeter
        echo "export PATH=\$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

    # Step 4: Install JMeter Plugins (using JMeter Plugin Manager)
    - name: Install JMeter Plugins
      run: |
        # Download and install the JMeter Plugins Manager
        wget https://jmeter-plugins.org/files/jmeter-plugins-manager-1.10.jar
        mv jmeter-plugins-manager-1.10.jar /opt/jmeter/lib/ext/
        cd  /opt/jmeter/bin/
        ./PluginsManagerCMD.sh install jpgc-dummy,jpgc-graphs-basic,jpgc-graphs-additional,jmeter-grpc-request


    # Step 5: Get the most recently modified .jtl file
    - name: Get latest .jtl file
      id: get_latest_file
      run: |
        latest_file=$(ls -t ./resultfileupload/*.jtl | head -n 1)
          
        # Ensure that a file was found
        if [ -z "$latest_file" ]; then
          echo "No .jtl file found!"
          exit 1
        fi

        echo "Latest file: $latest_file"
          
        # Set the latest file as an environment variable for later steps
        echo "latest_file=$latest_file" >> $GITHUB_ENV


    # Step 6: Create the CSV report from the .jtl file
    - name: Generate CSV from JTL file
      run: |
        # Use the latest .jtl file to generate the CSV report
        ./JMeterPluginsCMD.sh --generate-csv ./aggregated_report.csv \
          --input-jtl ${{ env.latest_file }} \
          --plugin-type AggregateReport \
          --exclude-label-regex true \
          --exclude-labels '.*\/.*|.*Token.*|.*BeanShell.*|bzm.*'

        # Ensure the generated CSV file exists
        if [ ! -f "./aggregated_report.csv" ]; then
          echo "CSV file was not created successfully."
          exit 1
        fi

    # Step 7: Commit the result file back to the repository
    - name: Commit result file
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Add result files generated by JMeter'
        add: './aggregated_report.csv'  # Only add the generated file
              
    # Step 8: Push changes to the repository
    - name: Push changes to repository
      run: |
        git push
