name: Run Python Script and Save Results

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  run-python-script:
    runs-on: ubuntu-latest  

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      # Step 4: Run the Python script
      - name: Run Python script
        run: python predictreport.py

      # Step 5: Commit the result file back to the repository
      - name: Commit result file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Add result files generated by Python script'
          add: './*'  # Add the result file to the commit
      
      # # Step 6: Deploy to GitHub Pages 
      # - name: Deploy HTML report to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./reports/final_stock_report.html  # HTML filepath
      #     publish_branch: gh-pages
